# Generated by Django 5.2.7 on 2025-11-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Описание'),
        ),
    ]
