version: '3.8'

services:
  api:
    image: $DOCKER_USERNAME/auto-service:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: always
    container_name: django
    env_file:
      - ../.env
    environment:
      DB_HOST: postgres
    volumes:
      - ./media:/app/media
      - ./.env:/app/.env

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    container_name: autoservice_postgres
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoservice_user -d autoservice_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: