# Generated by Django 5.2.7 on 2025-11-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='communication',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Ватсап')], max_length=10, verbose_name='Предпочтительный способ связи'),
        ),
    ]
