# Generated by Django 5.2.7 on 2025-11-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('address', 'Адрес'), ('schedule', 'График работы'), ('social', 'Соцсеть'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип контакта')),
                ('icon', models.CharField(help_text='Например: fas fa-phone, fas fa-map-marker-alt', max_length=50, verbose_name='Иконка Font Awesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка (для соцсетей)')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AutoExpert', max_length=100, verbose_name='Название сайта')),
                ('site_description', models.CharField(default='Профессиональный автосервис', max_length=200, verbose_name='Описание сайта')),
                ('company_name', models.CharField(default='ООО "АвтоЭксперт"', max_length=100, verbose_name='Название компании')),
                ('company_address', models.TextField(verbose_name='Полный адрес')),
                ('working_hours', models.TextField(verbose_name='График работы')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для связи')),
                ('phone', models.CharField(max_length=20, verbose_name='Основной телефон')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
