# Generated by Django 5.2.7 on 2025-11-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_delete_sitesettings_remove_contact_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.CharField(choices=[('fas fa-phone', '📞 Телефон'), ('fas fa-map-marker-alt', '📍 Адрес'), ('fas fa-envelope', '✉️ Email'), ('fas fa-clock', '🕒 График работы'), ('fas fa-car', '🚗 Автомобиль'), ('fas fa-tools', '🛠️ Инструменты'), ('fas fa-wrench', '🔧 Ремонт'), ('fas fa-oil-can', '🛢️ Масло'), ('fas fa-tire', '🎫 Шины'), ('fas fa-battery-full', '🔋 Аккумулятор'), ('fas fa-bolt', '⚡ Электрика'), ('fas fa-thermometer-half', '🌡️ Диагностика'), ('fab fa-whatsapp', '💚 WhatsApp'), ('fab fa-telegram', '✈️ Telegram'), ('fab fa-vk', '🔵 VKontakte'), ('fas fa-globe', '🌐 Сайт'), ('fas fa-user', '👤 Контактное лицо'), ('fas fa-building', '🏢 Компания'), ('fas fa-home', '🏠 Офис'), ('fas fa-subway', '🚇 Метро'), ('fas fa-bus', '🚌 Автобус'), ('fas fa-parking', '🅿️ Парковка')], default='fas fa-phone', max_length=50, verbose_name='Иконка'),
        ),
    ]
